### ISSUE TITLE
Dev Call Topic Collector

### ISSUE THREAD

**Issue by freimair** [bisq-network/events#31]
# Topic queue
- [x] Dev resources or "Why nobody reacts to stuff" [via](https://github.com/bisq-network/events/issues/27)
- [x] Seednodes: Goals and strategies on how to get seednodes more stable and reliable [via](https://github.com/bisq-network/events/issues/27)
- [ ] Seednodes: Compensation (https://github.com/bisq-network/proposals/issues/102) [via](https://github.com/bisq-network/events/issues/29)
- [x] Testing roadmap and strategies (https://github.com/bisq-network/proposals/issues/105) [via](https://github.com/bisq-network/events/issues/28)
- [x] How do we proceed with @blabno's API [via](https://github.com/bisq-network/events/issues/30) [via](https://github.com/bisq-network/events/issues/32)
- [x] How to attract more developers to the project (https://github.com/bisq-network/events/issues/27#issuecomment-521241780) [via](https://github.com/bisq-network/events/issues/29)
- [x] Kotlin in tests https://github.com/bisq-network/bisq/issues/3026 [via](https://github.com/bisq-network/events/issues/28)
- [ ] Kotlin https://github.com/bisq-network/bisq/issues/3026
- [ ] Asset rebranding - how to deal with it, how to protect against malicious takeover/delisting [via](https://github.com/bisq-network/events/issues/34)
- [ ] Asset governance - how is it done [via](https://github.com/bisq-network/events/issues/34)
- [ ] upgrading libs - best practice?
- [ ] Bisq on other Platforms - RPi, Android, ...
- [ ] shall we integrate third-party functionality into bisq core (eg. https://github.com/bisq-network/bisq/issues/3198)
- [x] a new Trade protocol [via](https://github.com/bisq-network/events/issues/33)
- [ ] incubator do's and don'ts
- [ ] PB may break Bisq https://github.com/bisq-network/bisq/issues/3391
- [ ] code formatting, use Travis?

please feel free to comment on additional topics of interest

**Comment by freimair** [comment]
- [x] What's next? Trader Chat, new Trade Protocol, ... [via](https://github.com/bisq-network/events/issues/33)

**Comment by ghost** [comment]
Only a humble (and a bit orthogonal) suggestion, but since github is the dev platform, maybe that devoting 15' each dev call to github tricks (by the knowledgeables) could be useful (?).

**Comment by freimair** [comment]
- [ ] provide walk-throughs of the project code
